name: CI - Service-Vendeur-Localisation
on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
      - uses: gitleaks/gitleaks-action@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install -y trivy

      - name: Docker build
        run: docker build -t soukscan-vendeur-localisation:latest .

      - name: Trivy scan (image)
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL soukscan-vendeur-localisation:latest

        on:
  push:
    branches: ["main"]   # change if your default branch isnâ€™t main
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

